package com.ecosystem.research.core.ecosystem

import android.content.Context
import android.content.Intent
import android.net.Uri
import com.ecosystem.research.core.model.Claim
import com.ecosystem.research.core.model.Evidence
import com.ecosystem.research.core.model.ResearchProject
import com.ecosystem.research.core.model.Source

enum class ThesisChapter(val code: String, val displayName: String, val defaultHeader: String) {
    CH1_INTRODUCTION("ch1", "Chapter 1: Introduction", "1. Introduction & Research Problem"),
    CH2_LITERATURE_REVIEW("ch2", "Chapter 2: Literature Review", "2. Literature Review & Prior Art"),
    CH3_METHODOLOGY("ch3", "Chapter 3: Methodology", "3. Methodology & Research Design"),
    CH4_RESULTS("ch4", "Chapter 4: Results", "4. Results & Empirical Observations"),
    CH5_DISCUSSION("ch5", "Chapter 5: Discussion", "5. Discussion, Limitations & Future Directions");

    companion object {
        fun fromTag(tag: String): ThesisChapter? {
            val normalized = tag.lowercase().removePrefix("thesis:").removePrefix("chapter:").removePrefix("ch")
            return values().firstOrNull { it.code == "ch$normalized" || it.name.equals(tag, ignoreCase = true) }
        }
    }
}

object DegreeTrackBridge {

    const val TAG_PREFIX = "thesis:"
    const val ACTION_DEGREE_MILESTONE = "com.ecosystem.action.DEGREE_TRACK_MILESTONE"

    fun formatChapterTag(chapter: ThesisChapter): String = "$TAG_PREFIX${chapter.code}"

    fun filterClaimsByChapter(claims: List<Claim>, chapter: ThesisChapter): List<Claim> {
        val targetTag = formatChapterTag(chapter)
        return claims.filter { claim ->
            // Check if claim notes or a simulated tag contains the chapter tag
            claim.notes?.contains(targetTag, ignoreCase = true) == true ||
                    claim.notes?.contains(chapter.code, ignoreCase = true) == true
        }
    }

    fun generateChapterBrief(
        project: ResearchProject,
        chapter: ThesisChapter,
        claims: List<Claim>,
        claimEvidenceMap: Map<String, List<Pair<Evidence, Source?>>>
    ): String {
        val sb = StringBuilder()
        sb.append("# ${project.title}\n")
        sb.append("## ${chapter.displayName}: ${chapter.defaultHeader}\n\n")

        if (project.primaryQuestion != null) {
            sb.append("**Guiding Research Question:** ${project.primaryQuestion}\n\n")
        }

        sb.append("### Formulated Hypotheses & Claims (${claims.size})\n\n")
        if (claims.isEmpty()) {
            sb.append("*No claims have been mapped to this chapter yet. Tag claims with `${formatChapterTag(chapter)}`.*\n\n")
        } else {
            claims.forEachIndexed { idx, claim ->
                sb.append("${idx + 1}. **${claim.proposition}** `[${claim.status.name}]`\n")
                val evidencePairs = claimEvidenceMap[claim.id] ?: emptyList()
                if (evidencePairs.isNotEmpty()) {
                    sb.append("   - **Evidence Grounding:**\n")
                    evidencePairs.forEach { (ev, src) ->
                        val citation = if (src != null) {
                            val author = if (src.authors.size > 1) {
                                "${src.authors.first()} et al."
                            } else {
                                src.authors.firstOrNull() ?: src.title
                            }
                            val year = src.year?.toString() ?: "n.d."
                            "$author ($year), p. ${ev.location.pageNumber}"
                        } else {
                            "p. ${ev.location.pageNumber}"
                        }
                        sb.append("     - *${ev.relationshipType.name}* [${citation}]: \"${ev.excerptText.trim()}\"\n")
                    }
                } else {
                    sb.append("   - *(No empirical evidence linked yet)*\n")
                }
                sb.append("\n")
            }
        }

        sb.append("---\n")
        sb.append("*Generated by Ecosystem Research App — DegreeTrack Thesis Integration*\n")
        return sb.toString()
    }

    fun createDegreeTrackMilestoneIntent(
        context: Context,
        projectId: String,
        projectTitle: String,
        chapter: ThesisChapter,
        evidenceCount: Int
    ): Intent {
        return Intent(ACTION_DEGREE_MILESTONE).apply {
            putExtra("project_id", projectId)
            putExtra("project_title", projectTitle)
            putExtra("chapter_code", chapter.code)
            putExtra("chapter_name", chapter.displayName)
            putExtra("evidence_count", evidenceCount)
            putExtra("timestamp", System.currentTimeMillis())
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
    }
}
